"""Foundation primitives shared across the runtime and configurator.

Imports nothing foundry-internal beyond stdlib + pydantic + anyio. The full
contract for what lives here is enumerated in docs/10-core-framework.md.
"""

from __future__ import annotations

from foundry.core.agent import Agent, AgentResult, BaseAgent, LifecycleHooks
from foundry.core.cache import (
    CacheAccessor,
    ResultCache,
    SemanticCache,
    SemanticCacheHit,
    SemanticCacheKey,
)
from foundry.core.connection import (
    AuthScheme,
    Connection,
    ConnectionAccessor,
    ConnectionContext,
    ConnectionDescriptor,
    ConnectionFactory,
    ConnectionHealth,
    ConnectionPool,
)
from foundry.core.embedder import (
    Embedder,
    EmbedderCapabilities,
    EmbedderPricing,
    Embedding,
)
from foundry.core.errors import (
    ApprovalRequired,
    CacheBackendError,
    CacheCorruptedEntry,
    CacheError,
    CheckpointError,
    CheckpointReadError,
    CheckpointWriteError,
    CompileError,
    ConfigError,
    ConfigLoadError,
    ConfigValidationError,
    ConnectionAuthError,
    ConnectionConfigError,
    ConnectionError,
    ConnectionHealthCheckError,
    ConnectionPoolExhausted,
    ConnectionRefreshError,
    ConnectionSlotNotBoundError,
    ConnectionSlotNotDeclaredError,
    ConnectionTimeoutError,
    CostBudgetExceeded,
    CyclicDependencyError,
    EmbedderAuthError,
    EmbedderConfigError,
    EmbedderError,
    EmbedderTimeoutError,
    EmbedderUnexpectedError,
    FoundryError,
    MaxHopsExceededError,
    MemoryConfigError,
    MemoryConsolidateError,
    MemoryError,
    MemoryLayerError,
    OrchestrationError,
    PinConflictError,
    ProviderAuthError,
    ProviderConfigError,
    ProviderContentPolicyError,
    ProviderError,
    ProviderRateLimitError,
    ProviderTimeoutError,
    ProviderUnexpectedError,
    RefResolutionError,
    RollbackError,
    RunCancelled,
    StateVisibilityError,
    ToolError,
    ToolHandlerError,
    ToolInputValidationError,
    ToolNotAllowedError,
    ToolNotFoundError,
    ToolOutputValidationError,
    UnknownPatternError,
    VersioningError,
)
from foundry.core.events import (
    AgentCompleted,
    AgentStarted,
    ApprovalRequiredEvent,
    ApprovalResolved,
    ApprovalResponse,
    CancelRun,
    ConnectionEvent,
    EmbedCall,
    FunctionNodeCompleted,
    FunctionNodeStarted,
    Handoff,
    InboundMessage,
    InjectInput,
    LLMCallCompleted,
    LLMCallStarted,
    LLMDelta,
    MemoryConsolidate,
    MemoryRead,
    MemoryWriteEvent,
    PauseRun,
    RerankEvent,
    ResumeRun,
    RetrievalEvent,
    RunCancelledEvent,
    RunCompleted,
    RunEvent,
    RunFailed,
    RunStarted,
    SemanticCacheHitEvent,
    SemanticCacheMiss,
    SemanticCacheStore,
    StateTransition,
    ToolCacheHit,
    ToolCompleted,
    ToolStarted,
)
from foundry.core.function_node import BaseFunctionNode, FunctionNode
from foundry.core.memory import (
    Memory,
    MemoryContext,
    MemoryContribution,
    MemoryEnvelope,
    MemoryLayer,
    MemoryWrite,
)
from foundry.core.messages import (
    ContentBlock,
    FoundryMessage,
    ImageBlock,
    MessageRole,
    TextBlock,
    ToolResultBlock,
    ToolUseBlock,
)
from foundry.core.model import (
    ModelDelta,
    ModelResponse,
    StopReason,
    TokenUsage,
    ToolUseBlockDelta,
)
from foundry.core.node import Node, NodeResult
from foundry.core.retrieval import Reranker, RetrievedDocument, Retriever
from foundry.core.session import (
    CancelToken,
    CheckpointerHandle,
    CostBudget,
    NoOpCheckpointer,
    Session,
)
from foundry.core.state import Reducer, StateBase
from foundry.core.tool import (
    BackoffStrategy,
    BaseTool,
    RetryPolicy,
    RunContext,
    Tool,
    ToolRegistry,
)
from foundry.core.types import (
    CacheControl,
    CredentialsRef,
    ResolvedCredentials,
    RunId,
)

__all__ = [
    "Agent",
    "AgentCompleted",
    "AgentResult",
    "AgentStarted",
    "ApprovalRequired",
    "ApprovalRequiredEvent",
    "ApprovalResolved",
    "ApprovalResponse",
    "AuthScheme",
    "BackoffStrategy",
    "BaseAgent",
    "BaseFunctionNode",
    "BaseTool",
    "CacheAccessor",
    "CacheBackendError",
    "CacheControl",
    "CacheCorruptedEntry",
    "CacheError",
    "CancelRun",
    "CancelToken",
    "CheckpointError",
    "CheckpointReadError",
    "CheckpointWriteError",
    "CheckpointerHandle",
    "CompileError",
    "ConfigError",
    "ConfigLoadError",
    "ConfigValidationError",
    # connection
    "Connection",
    "ConnectionAccessor",
    "ConnectionAuthError",
    "ConnectionConfigError",
    "ConnectionContext",
    "ConnectionDescriptor",
    "ConnectionError",
    "ConnectionEvent",
    "ConnectionFactory",
    "ConnectionHealth",
    "ConnectionHealthCheckError",
    "ConnectionPool",
    "ConnectionPoolExhausted",
    "ConnectionRefreshError",
    "ConnectionSlotNotBoundError",
    "ConnectionSlotNotDeclaredError",
    "ConnectionTimeoutError",
    "ContentBlock",
    "CostBudget",
    "CostBudgetExceeded",
    # types
    "CredentialsRef",
    "CyclicDependencyError",
    "EmbedCall",
    # embedder / retrieval / memory / cache
    "Embedder",
    "EmbedderAuthError",
    "EmbedderCapabilities",
    "EmbedderConfigError",
    "EmbedderError",
    "EmbedderPricing",
    "EmbedderTimeoutError",
    "EmbedderUnexpectedError",
    "Embedding",
    # errors
    "FoundryError",
    # messages
    "FoundryMessage",
    "FunctionNode",
    "FunctionNodeCompleted",
    "FunctionNodeStarted",
    "Handoff",
    "ImageBlock",
    "InboundMessage",
    "InjectInput",
    "LLMCallCompleted",
    "LLMCallStarted",
    "LLMDelta",
    "LifecycleHooks",
    "MaxHopsExceededError",
    "Memory",
    "MemoryConfigError",
    "MemoryConsolidate",
    "MemoryConsolidateError",
    "MemoryContext",
    "MemoryContribution",
    "MemoryEnvelope",
    "MemoryError",
    "MemoryLayer",
    "MemoryLayerError",
    "MemoryRead",
    "MemoryWrite",
    "MemoryWriteEvent",
    "MessageRole",
    "ModelDelta",
    # model
    "ModelResponse",
    "NoOpCheckpointer",
    # node / agent / function_node
    "Node",
    "NodeResult",
    "OrchestrationError",
    "PauseRun",
    "PinConflictError",
    "ProviderAuthError",
    "ProviderConfigError",
    "ProviderContentPolicyError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderTimeoutError",
    "ProviderUnexpectedError",
    "Reducer",
    "RefResolutionError",
    "RerankEvent",
    "Reranker",
    "ResolvedCredentials",
    "ResultCache",
    "ResumeRun",
    "RetrievalEvent",
    "RetrievedDocument",
    "Retriever",
    "RetryPolicy",
    "RollbackError",
    "RunCancelled",
    "RunCancelledEvent",
    "RunCompleted",
    "RunContext",
    # events
    "RunEvent",
    "RunFailed",
    "RunId",
    "RunStarted",
    "SemanticCache",
    "SemanticCacheHit",
    "SemanticCacheHitEvent",
    "SemanticCacheKey",
    "SemanticCacheMiss",
    "SemanticCacheStore",
    # session
    "Session",
    # state
    "StateBase",
    "StateTransition",
    "StateVisibilityError",
    "StopReason",
    "TextBlock",
    "TokenUsage",
    # tool
    "Tool",
    "ToolCacheHit",
    "ToolCompleted",
    "ToolError",
    "ToolHandlerError",
    "ToolInputValidationError",
    "ToolNotAllowedError",
    "ToolNotFoundError",
    "ToolOutputValidationError",
    "ToolRegistry",
    "ToolResultBlock",
    "ToolStarted",
    "ToolUseBlock",
    "ToolUseBlockDelta",
    "UnknownPatternError",
    "VersioningError",
]
