"""Config loading: YAML → typed Pydantic specs + composition + secrets.

Public surface: the ``load_*`` helpers and schema re-exports. No untyped
dicts leak past this layer (docs/12).
"""

from __future__ import annotations

from foundry.config.loader import (
    LoadedAgent,
    LoadedProject,
    load_agent_spec,
    load_connection_spec,
    load_eval_spec,
    load_function_node_spec,
    load_project,
    load_state_spec,
    load_system_spec,
    load_tool_spec,
)
from foundry.config.schemas import (
    AgentSpec,
    ConnectionBinding,
    ConnectionSlot,
    ConnectionSpec,
    EvalCase,
    EvalSpec,
    FieldSpec,
    FlowSpec,
    FunctionNodeSpec,
    GraphEdge,
    GraphFlow,
    Guardrails,
    HandoffPolicy,
    ObservabilityConfig,
    OutputSchemaRef,
    ParallelFlow,
    PoolPolicy,
    PromptRef,
    RefreshPolicy,
    ScorerConfig,
    SequentialFlow,
    SingleFlow,
    StateSpec,
    StateVisibility,
    SupervisorFlow,
    SystemSpec,
    TerminationRule,
    ToolBinding,
    ToolSpec,
)
from foundry.config.secrets import (
    EnvSecretsProvider,
    SecretsProvider,
    scan_for_secret_literals,
)

__all__ = [
    "AgentSpec",
    "ConnectionBinding",
    "ConnectionSlot",
    "ConnectionSpec",
    "EnvSecretsProvider",
    "EvalCase",
    "EvalSpec",
    "FieldSpec",
    "FlowSpec",
    "FunctionNodeSpec",
    "GraphEdge",
    "GraphFlow",
    "Guardrails",
    "HandoffPolicy",
    "LoadedAgent",
    "LoadedProject",
    "ObservabilityConfig",
    "OutputSchemaRef",
    "ParallelFlow",
    "PoolPolicy",
    "PromptRef",
    "RefreshPolicy",
    "ScorerConfig",
    "SecretsProvider",
    "SequentialFlow",
    "SingleFlow",
    "StateSpec",
    "StateVisibility",
    "SupervisorFlow",
    "SystemSpec",
    "TerminationRule",
    "ToolBinding",
    "ToolSpec",
    "load_agent_spec",
    "load_connection_spec",
    "load_eval_spec",
    "load_function_node_spec",
    "load_project",
    "load_state_spec",
    "load_system_spec",
    "load_tool_spec",
    "scan_for_secret_literals",
]
